package org.slello.security.exception

class UserNotFoundException : Exception()